openapi: 3.0.3
info:
  title: letsgo HTTP server - OpenAPI 3.0
  description: |-
    This is a HTTP server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
  termsOfService: http://swagger.io/terms/
  contact:
    email: najafizadeh21@gmail.com
  version: 0.1.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/v1
paths:
  /new:
    post:
      summary: Create a new record
      description: Create a new key-value pair
      parameters:
        - name: key
          in: query
          description: A key for the pair
          required: true
          schema:
            type: string
        - name: value
          in: query
          description: A value for the pair
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
  /get:
    get:
      summary: Get by key
      description: Get a key-value pair using the pair's key
      parameters:
        - name: key
          in: query
          description: A key for the pair
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                  value:
                    type: string
        '404':
          description: Invalid key
        '503':
          description: Server failed to parse the response
  /del:
    delete:
      summary: Delete by key
      description: Delete a key-value pair
      parameters:
        - name: key
          in: query
          description: A key for the pair
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Invalid key
